### PR TITLE
Add feature to spilit a db into files

### PR DESCRIPTION
**Pull request by eggers**
I saw that someone wanted this feature for json-server typicode/json-server#45, so I decided to play around with it. I had to make a extra statement in json-server as well to the end of bin/index.js

```js
// DIRECTORY
} else {
  console.log('directory')
  var path = process.cwd() + '/' + source
  if(fs.existsSync(path) && fs.statSync(path).isDirectory()) {
    var object = low(path).object
    start(object, path)
  }
}
```

### CODE REVIEW

**Comment by etiktin** [comment]
It's an interesting idea. Can you provide some usage examples so it will easier to figure out how to work with a directory?
From the code it seems that you load the files as keys in the db object which adds a level of indirection. Lets say that I load a directory that contains 2 files, `a.json` and `b.json` and `b.json` looks like this:
```
{
  "songs": [
    {
      "title": "First"
    }
}
```
Adding a song is possible by doing something like `db.object.b.songs.push({title: 'Second'});`.
How would you go about finding a song? I would expect something like `db.object.b.songs.find({title: 'First'});` to fail, because `find` is available on the `db` object and not on the keys (`b` in this case).

**Comment by eggers** [comment]
@etiktin I will try to add some information in the readme about how the saving/reading from a directory would work. But, the way I imagined it working would that you would have a folder `db` with files like `songs.json` and `titles.json`. `songs.json` would look like this:

```
[
  {
    "title": "First"
  }
]
```

Then, to do a find you'd do something like this:

```
var song   = db('songs').find({ title: 'First' })
```

Of course, in your example you might be able to do something like this: `db('b').pluck('songs').find({title: 'First'})` You might have to make some adjustments to get that to work though because it might be expecting `db.b` to be an `array`.

**Comment by etiktin** [comment]
Thanks for the explanation. I get it now :)

**Comment by typicode** [comment]
Thank you for the PR and sorry for not replying.
It's now possible using storage adapters so I'm closing it.

**Pull request closed without merging**
