### PR TITLE
Added typescript definition

### LINKED ISSUE #94: Provide a definitely typed file (.d.ts) for TypeScript
Unfortunately there is no .d.ts file for TypeScript, so that lowdb cannot be used with TypeScript.

### PR DESCRIPTION
**Pull request by chimon2000**
Resolves #94

I didn't see a contribution guide so I was unsure if I needed to add tests for a definition file. If so, I'll gladly do so.

### CODE REVIEW

**Comment by typicode** [comment]
Thank you @chimon2000, I may not keep lodash related definitions though. Mainly because it would be hard to keep lodash + lowdb definitions up to date.

BTW I've recently discovered https://github.com/DefinitelyTyped/DefinitelyTyped

I'm not very familiar with TypeScript how do you test a definition file?

**Comment by chimon2000** [comment]
@typicode I just created a basic test app and tested the various lodash functions. You can also just copy your current tests, rename all the files with 'ts', and change the import structure to test that way (probably the best option). You just need an extra build step on your server to compile & run that code just like you would do with Babel.

I thought about putting the definitions on DefinitelyTyped, but from what I've read the community will be trending away from that direction in the future, and a lot of the newer libraries (such as ava) include their definitions.

**Comment by chimon2000** [comment]
Actually I [stand corrected](https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/). It looks like moving them into DefinitelyTyped is/will still be viable.

**Comment by hastebrot** [comment]
>Mainly because it would be hard to keep lodash + lowdb definitions up to date.

Yes, that's true. For instance, `groupBy()` is now missing in `lowdb.d.ts`. 

I experimented a bit with the existing `lodash.d.ts` from `DefinitelyTyped` (or the npm package `@types/lodash`), and tried to integrate/reuse it for lowdb.

The main problem is, that there is a distinction between `LoDashExplicitObjectWrapper` and `LoDashExplicitArrayWrapper` in the type declarations. The compiler get the respective types in the "constructor" methods in `LoDashStatic` (`_(value)` and `_.chain(value)`):

~~~ts
(value: number): LoDashImplicitWrapper<number>;
(value: string): LoDashImplicitStringWrapper;
(value: boolean): LoDashImplicitWrapper<boolean>;
(value: Array<number>): LoDashImplicitNumberArrayWrapper;
<T>(value: Array<T>): LoDashImplicitArrayWrapper<T>;
<T extends {}>(value: T): LoDashImplicitObjectWrapper<T>;
(value: any): LoDashImplicitWrapper<any>;

chain(value: number): LoDashExplicitWrapper<number>;
chain(value: string): LoDashExplicitWrapper<string>;
chain(value: boolean): LoDashExplicitWrapper<boolean>;
chain<T>(value: T[]): LoDashExplicitArrayWrapper<T>;
chain<T extends {}>(value: T): LoDashExplicitObjectWrapper<T>;
chain(value: any): LoDashExplicitWrapper<any>;
~~~

Now we can do two different things. We can extend a new `interface LoDashWrapper<T>` from `LoDashExplicitObjectWrapper` and add the array methods:

~~~ts
interface LoDashWrapper<T> extends _.LoDashExplicitObjectWrapper<T> {
  // LoDashExplicitObjectWrapper.
  get<TResult>(
    path: _.StringRepresentable|_.StringRepresentable[],
    defaultValue?: any
  ): LoDashWrapper<TResult>;

  // LoDashExplicitArrayWrapper.
  pop(): _.LoDashExplicitObjectWrapper<T>;
  push(...items: T[]): _.LoDashExplicitArrayWrapper<T>;
  shift(): _.LoDashExplicitObjectWrapper<T>;
  sort(compareFn?: (a: T, b: T) => number): _.LoDashExplicitArrayWrapper<T>;
  splice(start: number): _.LoDashExplicitArrayWrapper<T>;
  splice(start: number, deleteCount: number, ...items: any[]): _.LoDashExplicitArrayWrapper<T>;
  unshift(...items: T[]): _.LoDashExplicitArrayWrapper<T>;

  chain<T>(value: T[]): _.LoDashExplicitArrayWrapper<T>;
  chain<T extends {}>(value: T): _.LoDashExplicitObjectWrapper<T>;
  chain<T>(value: any): _.LoDashExplicitWrapper<T>;
}
~~~

Or we can extend a new `interface LoDashWrapper<T>` from `LoDashExplicitArrayWrapper` and add the object methods:

~~~ts
interface LoDashWrapper<T> extends _.LoDashExplicitArrayWrapper<T> {
  // LoDashExplicitObjectWrapper.
  get<TResult>(
    path: _.StringRepresentable|_.StringRepresentable[],
    defaultValue?: any
  ): LoDashWrapper<TResult>;

  set<TResult>(
    path: _.StringRepresentable|_.StringRepresentable[],
    value: any
  ): LoDashWrapper<TResult>;

  set<V, TResult>(
    path: _.StringRepresentable|_.StringRepresentable[],
    value: V
  ): LoDashWrapper<TResult>;

  has(path: _.StringRepresentable|_.StringRepresentable[]): LoDashWrapper<boolean>
}
~~~

Either way, this has some disadvantages and is a rather ugly solution. I'm looking forward to try to let the user give the respective wrapper type using something like `db.get<any>()` (for the object type) and `db.get<any[]>()` (for the array type).

**Comment by hastebrot** [comment]
> I'm looking forward to try to let the user give the respective wrapper type using something like `db.get<any>()` (for the object type) and `db.get<any[]>()` (for the array type).

This plan does not seem to work. The compiler uses the method `get<T extends any[]>(...)` for `db.get<any[]>(...)`, but the return type is `ArrayWrapper<any[]>` instead of the desired `ArrayWrapper<any>`.

~~~ts
type ArrayWrapper<T> = _.LoDashExplicitArrayWrapper<T>;
type ObjectWrapper<T> = _.LoDashExplicitObjectWrapper<T>;
type Path = _.StringRepresentable|_.StringRepresentable[];

interface LoDashWrapper<T> extends ObjectWrapper<T> {
  get<T extends any[]>(path: Path, defaultValue?: any): ArrayWrapper<T>;
}
~~~

I'll go instead with another approach and use it in my code to gain more insights. It can be used with `db.<low.ArrayWrapper<any>>.get(...)` and works as expected so far.

~~~ts
type ArrayWrapper<T> = _.LoDashExplicitArrayWrapper<T>;
type ObjectWrapper<T> = _.LoDashExplicitObjectWrapper<T>;
type Path = _.StringRepresentable|_.StringRepresentable[];

interface LoDashWrapper<T> extends ObjectWrapper<T> {
  get<TResultWrapper extends ObjectWrapper<T>>(
    path: Path,
    defaultValue?: any
  ): TResultWrapper;

  get<TResultWrapper extends ArrayWrapper<T>>(
    path: Path,
    defaultValue?: any
  ): TResultWrapper;
}
~~~

**Comment by hastebrot** [comment]
Could probably remove `push()` et al from `LoDashWrapper` because using `[]` as root for the json lowdb file is not possible:

~~~ts
const db = low("dist/lowdb.json", {
  writeOnChange: false
})
db.setState(["foo"])
db.write()

db.push("bar")
db.write() // will write ["foo"].
~~~

**Pull request merged**
