### PR TITLE
Lazy creation of db file and exists method

### PR DESCRIPTION
**Pull request by etiktin**
This PR adds the following:
1. If the db file doesn't exist, it will be created only after the first db.save.
2. New method to check if the db exists. `low.exists(file)`.

### CODE REVIEW

**Comment by etiktin** [comment]
@typicode, what do you think?

**Comment by typicode** [comment]
Sorry for the late reply. That's some clever code.
But personally, I prefer to see a file created immediately when I call:

```javascript
var db = low('db.json')
```

And for `low.exist`, I think it's ok to not include it in `lowdb` and use `fs` directly.

**Comment by etiktin** [comment]
Thanks.
I understand your point about the lazy creation of the db file and respect it.
What about merging the `Improve efficiency of initial parse` commit? It's a really small change (2 lines) that can improve the loading time for large dbs.

Regarding `low.exists`, I think it makes sense to add an API call to test for the existence of the db. The reason is consistency across different back-ends. Currently lowdb works over the file system and all the back-end methods are in disk.js. If you (or someone else) would add another back-end to lowdb (for example mongodb) he/she can just implement the methods in disk.js. But if there's no exists method, users that want to check for db existence will have to resort to use some custom code for that specific back-end (it's a one-liner for fs, but that's not necessarily the case for other back-ends). Adding the method will make it easier to use (no need to understand how to talk to the back-end and no need to change code when switching back-end).

I think that it also makes sense to add `db.exists` for checking if a collection exists, because currently you don't have a way to do it, at least not without side-effects (see #42).
If we add both methods, checking for existence will be consistent and clear.

If you agree, let me know and I can open a new PR with just the relevant changes.

What do you think?

**Comment by typicode** [comment]
Sorry, didn't really understand what was `Improve efficiency of initial parse` doing.
If you could make a PR for this one, I'll be happy to merge.

For `exists` just give me some time.

Thank you for the detailed explanations :)

**Comment by etiktin** [comment]
Your welcome.
I'll open a separate PR for the efficiency commit.
For `exists`, take all the time that you need :smile:

**Pull request closed without merging**
